version: '3.7'
services:
  nginx:
    image: nginx
    container_name: relis-nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf

  db:
    container_name: relis-db
    image: mariadb
    restart: always
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"

    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

    volumes:
      - ./docker/db/initial_db.sql:/docker-entrypoint-initdb.d/initial_db.sql
      - ../data/db:/var/lib/mysql

  tomcat:
    depends_on:
      - db
    image: tomcat-relis
    build:
      context: ./tomcat/
      dockerfile: Dockerfile
    entrypoint: /usr/local/bin/entrypoint.sh
    env_file:
      - .env
    volumes:
      - ../:/u/relis/public_html
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    environment:
      MYSQL_DATABASE: db
      CATALINA_OPTS: '-Xms512M -Xmx1024M -server -XX:+UseParallelGC'
      JAVA_OPTS: '-Djava.security.egd=file:///dev/urandom'

  relis-application:
    depends_on:
      - db
    image: relis-app
    container_name: relis-app
    build:
      context: ./docker/
    env_file:
      - .env
    entrypoint: /usr/local/bin/entrypoint.sh
    restart: always
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    volumes:
      - ../:/u/relis/public_html
