version: '3.7'
services:
  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"

    deploy:
      replicas: 1

      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

    volumes:
      - ./docker/db/initial_db.sql:/docker-entrypoint-initdb.d/initial_db.sql
      - /u/relis/relisdb:/var/lib/mysql

  tomcat:
    depends_on:
      - db
    image: relis/tomcat-relis
    build:
      context: ./tomcat/
      args:
        - DOCUMENT_ROOT=/u/relis/public_html
        - DIRECTORY_INDEX=index.php
        - GROUP_ID=510
        - USER_ID=16001
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - ../:/u/relis/public_html
    networks:
      default:
        aliases:
          - relistomcat
    deploy:
      replicas: 1

      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    environment:
      MYSQL_DATABASE: db
      CATALINA_OPTS: '-Xms512M -Xmx1024M -server -XX:+UseParallelGC'
      JAVA_OPTS: '-Djava.security.egd=file:///dev/urandom'

  bibler:
    image: relis/bibler:latest
    restart: always
    environment:
      ENV: "prod"

    deploy:
      replicas: 3

      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

  relis-application:
    depends_on:
      - db
    image: relis/relis-app
    build:
      context: ./docker/
      args:
        - DOCUMENT_ROOT=/u/relis/public_html
        - DIRECTORY_INDEX=index.php
        - GROUP_ID=510
        - USER_ID=16001
    env_file:
      - .env
    entrypoint: /usr/local/bin/entrypoint.sh
    restart: always
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    volumes:
      - ../:/u/relis/public_html
